version: '3'
services:
  recipes-api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/recipes
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=MyP@ssw0rd
    ports:
      - 8080:8080
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: recipes
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: MyP@ssw0rd
    ports:
      - 54321:5432
    volumes:
      - pgdb:/var/lib/postgresql/data

volumes:
  pgdb:
